




document.addEventListener("DOMContentLoaded", function () {
    const articles = [
        {
          "title": "From Models to Practice: Enhancing OSS Project Sustainability with Evidence-Based Advice",
          "link": "https://www.cs.ucdavis.edu/~filkov/papers/react.pdf",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Vladimir Filkov",
          "image": "img/react_paper.png",
          "description": "Sustainability in Open Source Software (OSS) projects is crucial for long-term innovation, community support, and the enduring success of open-source solutions. Although multitude of studies have provided effective models for OSS sustainability, their practical implications have been lacking because most identified features are not amenable to direct tuning by developers (e.g., levels of communication, number of commits per project). \n\n      In this paper, we report on preliminary work toward making models more actionable based on evidence-based findings from prior research. Given a set of identified features of interest to OSS project sustainability, we performed a comprehensive literature review related to those features to uncover practical, evidence-based advice, which we call Researched Actionables (ReACTs). The ReACTs are practical advice with specific steps, found in prior work to associate with tangible results. Starting from a set of sustainability-related features, this study contributes 105 ReACTs to the SE community by analyzing 186 published articles. Moreover, this study introduces a newly developed tool (ReACTive) designed to enhance the exploration of ReACTs through visualization across various facets of the OSS ecosystem. The ReACTs idea opens new avenues for connecting SE metrics to actionable research in SE in general."
        },
        {
          "title": "Leveraging Language Models to Discover Evidence-Based Actions for OSS Sustainability",
          "link": "",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Vladimir Filkov",
          "image": "img/EvidenceBotArchitecture.png",
          "description": "When successful, Open Source Software (OSS) projects can provide tremendous economic value for society, but the road to their success is not straightforward. Keeping a project on the trajectory to success calls for effective and actionable models for forecasting their sustainability. However, the distributed, multilayered structures of OSS projects make it challenging for practitioners to map model features to specific actions. Consequently, there is a pressing need for actionable recommendations derived from empirical evidence, coming out of prior studies which have established direct links between model features and actionable outcomes.\n\n      In this study, we propose a Retrieval-Augmented Generation (RAG)-based pipeline that employs a combination of traditional and strategic LLM prompting techniques to extract actionable recommendations from scientific articles in Software Engineering. Our two-layered approach first utilizes conventional prompting to identify actionables, followed by a follow-up prompting technique to supplement these insights with contextual information, enhancing their practical applicability. Through a comprehensive analysis of 823 articles published in top-ranked Software Engineering venues in the 21st century, we have extracted 2,234 actionable recommendations. This research not only addresses potential concerns of using Large Language Models (LLMs) for such tasks but also provides a robust methodology for deriving and evaluating actionable insights. The adaptation of these recommendations has the potential to aid thousands of OSS projects that may be at risk at any given time, potentially saving valuable resources."
        },
        {
          "title": "Modeling Sustainability of OSS Projects Across and Outside of the Apache and Eclipse Foundations",
          "link": "",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Arjun Ashok, Swati Singhvi, \u0218tefan St\u0103nciulescu, Vladimir Filkov",
          "image": "img/apache_eclipse_grad_forecast.png",
          "description": "Despite the paramount importance of OSS projects, many fail due to a lack of coordination and community-building support. As contributions to OSS projects are often not directly incentivized, the trajectory to achieve success and remain sustainable is complex and can depend on many implicit factors. To enhance their development trajectories, projects join foundations such as Apache, Eclipse, Linux, and others. Often, those foundations work by implicitly and/or explicitly modifying the actions and governance of the projects and offering tailored suggestions and support to build effective and diverse communities of developers. However, the foundations differ significantly in key aspects, including their policies, incubation models, funding, and project support mechanisms. This diversity makes planning for sustainability a complex process for individual projects.\n\n      In this paper, we conducted an in-depth empirical study of projects from two open-source foundations, Apache and Eclipse, to identify implicit differences between them through building models of sustainability in each. We demonstrate that when trained on data from individual foundations\u2019 projects, our robust machine-learning models are capable of effectively predicting project sustainability outcomes. Moreover, the models prove more effective when trained on data from both foundations. Leveraging prior work, we map the models\u2019 significant features to actionable recommendations during project downturns. Finally, we applied the jointly trained models to case studies of several failed projects from both within and outside the foundations. Based on our analysis, we provide retrospective actionable suggestions that could have altered the projects' trajectories."
        },
        {
          "title": "COVID-19 and Black Fungus: Analysis of Public Perceptions through Machine Learning",
          "link": "https://onlinelibrary.wiley.com/doi/10.1002/eng2.12475",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Tahasin Mahmud, and Muhammad Nazrul Islam",
          "image": "img/fungus.jpg",
          "description": "While COVID-19 is ravaging the lives of millions of people across the globe, a second pandemic \u201cblack fungus\u201d has surfaced robbing people of their lives especially people who are recovering from coronavirus. Thus, the objective of this article is to analyze public perceptions through sentiment analysis regarding black fungus during the COVID-19 pandemic. To attain the objective, first, a support vector machine (SVM) model, with an average AUC of 82.75%, was developed to classify user sentiments in terms of anger, fear, joy, and sad. Next, this SVM model was used to predict the class labels of the public tweets (n = 6477) related to COVID-19 and black fungus. As outcome, this article found public perceptions towards black fungus during COVID-19 pandemic belong mostly to sad (n= 2370, 36.59%), followed by joy (n = 2095, 32.34%), fear (n = 1914, 29.55%) and anger (n = 98, 1.51%). This article also found that public perceptions are varied to some critical concerns like education, lockdown, hospital, oxygen, quarantine, and vaccine. For example, people mostly exhibited fear in social media about education, hospital, vaccine while some people expressed joy about education, hospital, vaccine, and oxygen. Again, it was found that mass people have an ignorance tendency to lockdown, COVID-19 restrictions, and prescribed hygiene rules although the coronavirus and black fungus infection rates broke the previous infection records."
        },
        {
          "title": "Exploring machine learning algorithms to find the best features for predicting modes of childbirth",
          "link": "https://ieeexplore.ieee.org/abstract/document/9296752",
          "authors": "Muhammad Nazrul Islam, Tahasin Mahmud, <b>Nafiz Imtiaz Khan</b>, Sumaiya Nuha Mustafina, A. K. M. Najmul Islam",
          "image": "img/childbirth.jpg",
          "description": "The mode of delivery is a crucial determinant for ensuring the safety of both mother and child. The current practice for predicting the mode of delivery is generally the opinion of the physician in charge, but choosing the wrong method of delivery can cause different short-term and long-term health issues for both mother and baby. The purpose of this study was twofold: first, to reveal the possible features for determining the mode of childbirth, and second, to explore machine learning algorithms by considering the best possible features for predicting the mode of childbirth (vaginal birth, cesarean birth, emergency cesarean, vacuum extraction, or forceps delivery). An empirical study was conducted, which included a literature review, interviews, and a structured survey to explore the relevant features for predicting the mode of childbirth, while five different machine learning algorithms were explored to identify the most significant algorithm for prediction based on 6157 birth records and a minimum set of features. The research revealed 32 features that were suitable for predicting modes of childbirth and categorized the features into different groups based on their importance. Various models were developed, with stacking classification (SC) producing the highest f1 score (97.9%) and random forest (RF) performing almost as well (f1-score = 97.3%), followed by k-nearest neighbors (KNN; f1-score = 95.8%), decision tree (DT; f1-score = 93.2%), and support vector machine (SVM; f1-score = 88.6%) techniques, considering all (n = 32) features."
        },
        {
          "title": "VGG-SCNet: A VGG Net-Based Deep Learning Framework for Brain Tumor Detection on MRI Images",
          "link": "https://ieeexplore.ieee.org/abstract/document/9515947",
          "authors": "Mohammad Shahjahan Majib, Md. Mahbubur Rahman, T. M. Shahriar Sazzad, <b>Nafiz Imtiaz Khan</b>, Samrat Kumar Dey",
          "image": "img/vgg.png",
          "description": "A brain tumor is a life-threatening neurological condition caused by the unregulated development of cells inside the brain or skull. The death rate of people with this condition is steadily increasing. Early diagnosis of malignant tumors is critical for providing treatment to patients, and early discovery improves the patient\u2019s chances of survival. The patient\u2019s survival rate is usually very less if they are not adequately treated. If a brain tumor cannot be identified in an early stage, it can surely lead to death. Therefore, early diagnosis of brain tumors necessitates the use of an automated tool. The segmentation, diagnosis, and isolation of contaminated tumor areas from magnetic resonance (MR) images is a prime concern. However, it is a tedious and time-consuming process that radiologists or clinical specialists must undertake, and their performance is solely dependent on their expertise. To address these limitations, the use of computer-assisted techniques becomes critical. In this paper, different traditional and hybrid ML models were built and analyzed in detail to classify the brain tumor images without any human intervention. Along with these, 16 different transfer learning models were also analyzed to identify the best transfer learning model to classify brain tumors based on neural networks. Finally, using different state-of-the-art technologies, a stacked classifier was proposed which outperforms all the other developed models. The proposed VGG-SCNet\u2019s (VGG Stacked Classifier Network) precision, recall, and f1 scores were found to be 99.2%, 99.1%, and 99.2% respectively."
        },
        {
          "title": "Data-driven shear strength prediction of steel fiber reinforced concrete beams using machine learning approach",
          "link": "https://www.sciencedirect.com/science/article/abs/pii/S0141029620343443",
          "authors": "Jesika Rahmana, Khondaker Sakil Ahmed, <b>Nafiz Imtiaz Khan</b>, Kamrul Islam, Sujith Mangalathu",
          "image": "img/sfrc.jpeg",
          "description": "The incorporation of steel fibers in a concrete mix enhances the shear capacity of reinforced concrete beams and a comprehensive understanding of this phenomenon is imperative to have an accurate estimation in engineering designs. Although significant studies have been carried out on shear capacity estimation, mechanics-based models are not yet available due to the complex underlying phenomenon. This paper presents a data-driven approach to the shear strength of SFRC beams and incorporates the largest database compilation of 507 experimental data. Input features considered in this study are the ratio of shear span to effective depth, concrete compressive strength, longitudinal reinforcement ratio, volume fraction, aspect ratio, and type of fiber. Eleven machine learning (ML) models, namely linear regression, ridge regression, lasso regression, decision tree, random forest, support vector machine, k-nearest neighbors, artificial neural network, XGBoost, AdaBoost, and CatBoost, are evaluated to examine their shear strength estimation of SFRC beams. The XGBoost is resulting in the most accurate predictions (85%) with the lowest root mean squared error and low mean absolute error. A study on the importance of the input parameters reveals that shear span to effective depth ratio, longitudinal reinforcement ratio, concrete strength, and volume fraction of fiber are the most influential parameters of shear strength of SFRC."
        },
        {
          "title": "UVC-PURGE: A Novel Cost-Effective Disinfection Robot for Combating COVID-19 Pandemic",
          "link": "https://ieeexplore.ieee.org/abstract/document/9745041",
          "authors": "Akib Zaman, Mohammad Shahjahan Majib, Shoeb Ahmed Tanjim, Shah Md. Ahasan Siddique, Shafayetul Islam, Md Shadman Aadeeb, <b>Nafiz Imtiaz Khan</b>, Riasat Haque, Md Rashid Ul Islam, M. Rayhan Ferdous Faisal, Siddharth Malik, and Muhammad Nazrul Islam",
          "image": "img/uvc.gif",
          "description": "During the COVID-19 pandemic, surface disinfection using prevailing chemical disinfection methods had several limitations. Due to cost-inefficiency and the inability to disinfect shaded places, static UVC lamps cannot address these limitations properly. Moreover, the average market price of the prevailing UVC robots is huge, approximately 55,165 USD. In this research firstly, a requirement elicitation study was conducted using a semi-structured interview approach to reveal the requirements to develop a cost-effective UVC robot. Secondly, a semi-autonomous robot named UVC-PURGE was developed based on the revealed requirements. Thirdly, a two-phased evaluation study was undertaken to validate the effectiveness of UVC-PURGE to inactivate the SARS-CoV-2 virus and the capability of semi-autonomous navigation in the first phase and to evaluate the usability of the system through a hybrid approach of SUPR-Q forms and subjective evaluation of the user feedback in the second phase. Pre-treatment swab testing revealed the presence of both Gram-positive and Gram-Negative bacteria at 17 out of 20 test surfaces in the conducted tests. After the UVC irradiation of the robot, the microbial load was detected in only 2 (1D and 1H) out of 17 test surfaces with significant reductions (95.33% in 1D and 90.9% in 1H) of microbial load. Moreover, the usability evaluation yields an above-average SUPR-Q score of 81.91% with significant scores in all the criteria (usability, trust, loyalty, and appearance) and the number of positive themes from the subjective evaluation using thematic analysis is twice the number of negative themes. Additionally, compared with the prevailing UVC disinfection robots in the market, UVC-PURGE is cost-effective with a price of less than 800 USD. Moreover, small form factor along with the real time camera feedback in the developed system helps the user to navigate in congested places easily. The developed robot can be used in any indoor environment in this prevailing pandemic situation and it can also provide cost-effective disinfection in medical facilities against the long-term residual effect of COVID-19 in the post-pandemic era."
        },
        {
          "title": "Predicting Bearing Capacity of Double Shear Bolted Connections Using Machine Learning",
          "link": "https://www.sciencedirect.com/science/article/abs/pii/S014102962101600X",
          "authors": "Samia Zakir Sarothi, Khondaker Sakil Ahmed, <b>Nafiz Imtiaz Khan</b>, Aziz Ahmed, and Moncef Nehdi",
          "image": "img/bolt.png",
          "description": "This study pioneers the application of machine learning (ML) for predicting the bearing strength of double shear bolted connections in structural steel. For the first time, a comprehensive database comprising 443 experimental datasets was compiled, with input features including the normalized end distance, edge distance, bolt pitch along and transverse to the loading directions of the connection, ultimate-to-yield strength ratio of the steel plate, number of bolt rows, connection configuration and normalized bearing capacity. Eleven ML techniques were explored for this application. Feature importance analysis identified the normalized end and edge distances as the most influential parameters on the ultimate bearing capacity. The performance of the models was evaluated using various statistical metrics and compared with existing formulations and design code provisions. Among all ML models, Random Forest was the best performing model, attaining the highest coefficient of determination (0.88), lowest mean absolute error (0.14), and lowest mean square error (0.26). Unlike existing models that are specific to certain steel grades and provide different equations for different failure modes, ML models accomplished an integrated and generalized predictive approach with an acceptable level of accuracy. Interestingly, ML models revealed that the ultimate-to-yield strength ratio of steel and the numbers of bolt rows, which are currently ignored by design guidelines, do influence the bearing strength significantly (nearly 10% each). A user-friendly interface comprising all proposed ML algorithms was developed to ease the design process of double shear bolted connections and serve as an educational and research tool for applying ML techniques to predicting the bearing strength of double shear bolted connections."
        },
        {
          "title": "Machine Learning-Based Failure Mode Identification of Double Shear Bolted Connections in Structural Steel",
          "link": "https://www.sciencedirect.com/science/article/abs/pii/S1350630722004459",
          "authors": "Samia Zakir Sarothi, Khondaker Sakil Ahmed, <b>Nafiz Imtiaz Khan</b>, Aziz Ahmed, and Moncef Nehdi",
          "image": "img/failure.png",
          "description": "The design of double shear bolted connections in structural steel is governed by four different failure modes; tear out, splitting, net-section, and bearing. Ten machine learning (ML) approaches were explored on a comprehensive database of 455 experimental results for identifying the failure modes of double shear bolted connections. Among them, Random Forest (RF), CatBoost, XGBoost, and Gradient Boosting (GB) attained 90\u201392% accuracy on the testing dataset for classifying the failure modes. The best-performing models revealed that the ratio of the edge distance-to-bolt diameter (e2/d0) is the most important feature with an influence of nearly 30% on the failure mode of the connections. Interestingly, the number of bolt rows in a connection also influences the failure mode, which was not captured by existing equations and design codes. Finally, a user interface capturing all proposed ML models was developed to identify the failure modes of double shear bolted connections."
        },
        {
          "title": "Machine learning to predict pregnancy outcomes: a systematic review, synthesizing framework and future research agenda. BMC pregnancy and childbirth",
          "link": "https://bmcpregnancychildbirth.biomedcentral.com/articles/10.1186/s12884-022-04594-2",
          "authors": "Muhammad Nazrul Islam, Sumaiya Nuha Mustafina, Tahasin Mahmud, and <b>Nafiz Imtiaz Khan</b>",
          "image": "img/agenda.png",
          "description": "Machine Learning (ML) has been widely used in predicting the mode of childbirth and assessing the potential maternal risks during pregnancy. The primary aim of this review study is to explore current research and development perspectives that utilizes the ML techniques to predict the optimal mode of childbirth and to detect various complications during childbirth. A total of 26 articles (published between 2000 and 2020) from an initial set of 241 articles were selected and reviewed following a Systematic Literature Review (SLR) approach. As outcomes, this review study highlighted the objectives or focuses of the recent studies conducted on pregnancy outcomes using ML; explored the adopted ML algorithms along with their performances; and provided a synthesized view of features used, types of features, data sources and its characteristics. Besides, the review investigated and depicted how the objectives of the prior studies have changed with time being; and the association among the objectives of the studies, uses of algorithms, and the features. The study also delineated future research opportunities to facilitate the existing initiatives for reducing maternal complacent and mortality rates, such as: utilizing unsupervised and deep learning algorithms for prediction, revealing the unknown reasons of maternal complications, developing usable and useful ML-based clinical decision support systems to be used by the expecting mothers and health professionals, enhancing dataset and its accessibility, and exploring the potentiality of surgical robotic tools. Finally, the findings of this review study contributed to the development of a conceptual framework for advancing the ML-based maternal healthcare system. All together, this review will provide a state-of-the-art paradigm of ML-based maternal healthcare that will aid in clinical decision-making, anticipating pregnancy problems and delivery mode, and medical diagnosis and treatment."
        },
        {
          "title": "Leveraging machine learning to analyze sentiment from COVID\u201019 tweets: A global perspective",
          "link": "https://onlinelibrary.wiley.com/doi/full/10.1002/eng2.12572",
          "authors": "Md Mahbubar Rahman, <b>Nafiz Imtiaz Khan</b>, Iqbal H. Sarker, Mohiuddin Ahmed, and Muhammad Nazrul Islam",
          "image": "img/leveraging.jpg",
          "description": "Since the advent of the worldwide COVID-19 pandemic, analyzing public sentiment has become one of the major concerns for policy and decision-makers. While the priority is to curb the spread of the virus, mass population (user) sentiment analysis is equally important. Though sentiment analysis using different state-of-the-art technologies has been focused on during the COVID-19 pandemic, the reasons behind the variations in public sentiment are yet to be explored. Moreover, how user sentiment varies due to the COVID-19 pandemic from a cross-country perspective has been less focused on. Therefore, the objectives of this study are: to identify the most effective machine learning (ML) technique for classifying public sentiments, to analyze the variations of public sentiment across the globe, and to find the critical contributing factors to sentiment variations. To attain the objectives, 12,000 tweets, 3000 each from the USA, UK, and Bangladesh, were rigorously annotated by three independent reviewers. Based on the labeled tweets, four different boosting ML models, namely, CatBoost, gradient boost, AdaBoost, and XGBoost, are investigated. Next, the top performed ML model predicted sentiment of 300,000 data (100,000 from each country). The public perceptions have been analyzed based on the labeled data. As an outcome, the CatBoost model showed the highest (85.8%) F1-score, followed by gradient boost (84.3%), AdaBoost (78.9%), and XGBoost (83.1%). Second, it was revealed that during the time of the COVID-19 pandemic, the sentiments of the people of the three countries mainly were negative, followed by positive and neutral. Finally, this study identified a few critical concerns that impact primarily varying public sentiment around the globe: lockdown, quarantine, hospital, mask, vaccine, and the like."
        },
        {
          "title": "Prediction of Cesarean Childbirth using Ensemble Machine Learning Methods",
          "link": "https://dl.acm.org/doi/10.1145/3428757.3429138",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Tahasin Mahmud, Muhammad Nazrul Islam, and Sumaiya Nuha Mustafina",
          "image": "img/ab.png",
          "description": "Cesarean section around the world is increasing at an alarming rate. Cesarean section, on one hand, may introduce different short-term and long-term complications for mother; on another hand it may be a life-saving procedure for both mother and child, depending on childbirth complications. The purpose of this research is to predict whether or not the cesarean section is necessary with the help of data mining and consequently, increasing the safety of the mother and newborn during and after childbirth by avoiding unnecessary cesarean section. To attain the objective three different ensemble prediction models based on- XGBoost, AdaBoost and Catboost were developed. As an outcome XGBoost showed the highest accuracy-88.91% while AdaBoost showed 88.69% accuracy and Catboost showed 87.66% accuracy. This research also revealed that amniotic liquid, medical indication, fetal intrapartum ph, number of previous cesareans, pre-induction are the most influential features for predicting the target outcome accurately."
        },
        {
          "title": "Evaluation of User's Emotional Experience through Neurological and Physiological Measures in Playing Serious Games",
          "link": "https://link.springer.com/chapter/10.1007/978-3-030-71187-0_96",
          "authors": "Tarannum Zaki, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam",
          "image": "img/features.JPG",
          "description": "The importance of evaluating user experience (UX) is increasing gradually and so are the varieties of methods of UX evaluation. In order to keep the interactive computing and entertaining system sustainable in business, satisfying the user needs is a must, while UX evaluation plays a vital role in this respect. Again, gaming experience is largely impacted by users\u2019 emotions. Among various types of games, serious game is a particular type which provides some purpose along with common gaming entertainment. The objective of this research is to show how objective methods (neurological and physiological measures) can be used to infer users\u2019 emotional experience. To attain this objective, a machine learning-based approach considering both the neurological and physiological measures is proposed to evaluate the users\u2019 emotions (UX) while playing serious game. The proposed approach is simulated through an experimental study to evaluate UX of an educational serious game \u2013\u2018Programming Hero\u2019. The finding of the study indicates that neurological and physiological measures of UX evaluation can infer the users\u2019 emotions in playing serious game."
        },
        {
          "title": "Exploring the Machine Learning Algorithms to Find the Best Features for Predicting the Breast Cancer and its Recurrence",
          "link": "https://link.springer.com/chapter/10.1007/978-3-030-68154-8_48",
          "authors": "Anika Islam Aishwarja, Nusrat Jahan Eva, Shakira Mushtary, Zarin Tasnim, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam",
          "image": "img/breast_cancner_prediction.png",
          "description": "Every year around one million women are diagnosed with breast cancer. Conventionally it seems like a disease of the developed countries, but the fatality rate in low and middle-income countries is preeminent. Early detection of breast cancers turns out to be beneficial for clinical and survival outcomes. Machine Learning Algorithms have been effective in detecting breast cancer. In the first step, four distinct machine learning algorithms (SVM, KNN, Naive Bayes, Random forest) were implemented to show how their performance varies on different datasets having different set of attributes or features by keeping the same number of data instances, for predicting breast cancer and it\u2019s recurrence. In the second step, analyzed different sets of attributes that are related to the performance of different machine learning classification algorithms to select cost-effective attributes. As outcomes, the most desirable performance was observed by KNN in breast cancer prediction and SVM in recurrence of breast cancer. Again, Random Forest predicts better for recurrence of breast cancer and KNN for breast cancer prediction, while the less number of attributes were considered in both the cases."
        },
        {
          "title": "Prediction of Android Malicious Software using boosting Algorithms",
          "link": "https://link.springer.com/chapter/10.1007/978-3-030-90016-8_2",
          "authors": "Deepon Deb Nath, <b>Nafiz Imtiaz Khan</b>, Jesmin Akhter and Abu Sayed Md. Mostafizur Rahaman",
          "image": "img/malware.png",
          "description": "Android malware, a group of malicious software variants, including viruses, ransomware and spyware, designed to cause substantial damage to data and systems or to access a network without authorization. With an inexorable shift in technology, Android has supplanted other Mobile platforms by being flexible and user-friendly to the users. As the number of Android apps continues to grow every day, the number of malwares aimed at attacking those users is also on the rise. Thus, it becomes emergent to identify and remove malicious Android applications before installation to prevent user\u2019s loss. Several studies have already been carried out to anticipate Android malware using machine learning algorithms, while as per the literature survey conducted by this study, a significant research has not been found to be focusing especially on the genre of boosting algorithms. Therefore, the objective of this paper is to classify malicious and benign Android applications by using Boosting algorithm. To attain the research objective, four widely defined boosting models viz. AdaBoost, CatBoost, XGBoost, and GradientBoost were developed whereas, it was found that CatBoost and GradientBoost had the highest F1 score (93.9%), followed by Adaboost (F1 score 93.5%), and XGBoost (F1 score 93.5%)."
        },
        {
          "title": "Design, Development and Evaluation of a Physical Exercise Monitoring and Managing System for Athletes",
          "link": "https://dl.acm.org/doi/abs/10.1145/3487664.3487725",
          "authors": "Noor Nafiz Islam, <b>Nafiz Imtiaz Khan</b>, Md Abdur Razzak, and Muhmmad Nazrul Islam",
          "image": "img/dsr.png",
          "description": "The worldwide sports industry is booming through the usage of information and communication technologies. The collection, analysis, and presentation of athlete data is common practice for professional individual and team sports to assess individuals (athletes)/teams capability, fatigue, and subsequent adaptation responses; examine potential improvement areas, and minimize the risk of injury. Nutrition and exercise plans are also blended to meet specific training requirements and build strategic programs to maximize athletes\u2019 ability to perform. An effective and efficient system is required for the athletes and their mentors to monitor and manage the athlete\u2019s physical exercise. Therefore, the purpose of this article is to reveal the user requirements for creating an athlete monitoring system and to propose a wearable system based on the revealed requirements. To achieve these objectives, a Design Science Research (DSR) approach was adopted. As such, an empirical study (through semi-structured interviews) was conducted with 41 participants to reveal the system requirements; then a wearable athlete monitoring application was developed considering the revealed requirements. Finally, the proposed system was evaluated with 21 participants through the System Usability Scale (SUS) method. The study found that the proposed system is reliable, user-friendly, and useful for monitoring and managing physical exercise for the athletes and their mentors. The study also showed that the proposed system is useful and usable regardless of the athlete\u2019s age or gender."
        },
        {
          "title": "Towards Developing a Mobile Application for Detecting Intoxicated People through Interactive UIs",
          "link": "https://link.springer.com/chapter/10.1007/978-981-19-0332-8_15",
          "authors": "Ifath Ara, Tasneem Mubashshira, Fariha Fardina Amin, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam",
          "image": "img/intoxication.jpg",
          "description": "Alcohol and Cannabis are among the most frequently used drugs worldwide. Excessive drinking is one of the leading lifestyle-related causes of death across the whole world. Both alcohol and cannabis can cause short-term problems with thinking, remembering, concentrating, and performing psycho-motor tasks. Taking drugs like alcohol and cannabis can impair a person\u2019s ability to perform tasks such as driving a car, flying an airplane, and making critical decisions. Clinical dope test methods are time-consuming, and instant testing devices, such as breathalyzers, are only available to law enforcement personnel which is expensive. Therefore, detecting intoxicated people using ubiquitous devices such as smartphones without any use of external hardware can be a cost-effective, time-saving, and efficient approach for ensuring safe performance in critical tasks. Hence, the objective of this research is to propose a conceptual framework for developing an interactive mobile application that detects intoxicated people by measuring behavioral abnormalities caused by alcohol and cannabis consumption. To accomplish this objective, the effects of alcohol and cannabis are investigated, followed by a review of the available tests in the literature. The proposed conceptual model encompasses testing of balancing capability, grip sense, simple reaction time, choice reaction time, short-time memory, and measuring a person\u2019s heart rate using tasks based on the short-term effects of alcohol and cannabis. Prototypes of the user interfaces are also developed based on the proposed conceptual framework."
        },
        {
          "title": "Sentiment Analysis of Bangladesh-specific COVID-19 Tweets using Deep Neural Network",
          "link": "https://ieeexplore.ieee.org/document/9615331",
          "authors": "Muhammad Nazrul Islam, <b>Nafiz Imtiaz Khan</b>, Ayon Roy, Md Mahbubar Rahman, Md Saddam Hossain Mukta, A.K.M Najmul Islam",
          "image": "img/covid_sentiment.png",
          "description": "Nowadays, social media became a tracker of the COVID-19 disease which reflects the status of the COVID-19 outbreak in the world. Although it is important to know the impact of COVID- 19 on the sentiment of mass people for the government and the policymakers in order to address peoples\u2019 needs and take emergent decisions during such crisis time, not many studies have been conducted regarding this issue. Moreover, very few studies were conducted on sentiment analysis during the COVID-19 pandemic in the context of Bangladesh. The purpose of this study is to estimate the impact of the COVID-19 outbreak on the sentiment of the Bangladeshi people through a machine learning approach. To achieve this goal, COVID-19 tweets were collected over a specific period and then build a deep learning classifier, having an average area under the curve (AUC) of 0.76. The study analyzes the spread and estimates various public emotions during the outbreak. And reveals that a significant number (55%) of people had negative sentiment regarding COVID-19, whereas, 38% and 7% of people had positive and neutral sentiment respectively. This study also found that people\u2019s involvement with social media increases as the number of active COVID-19 cases increases. Moreover, this study identified people\u2019s sentiment towards some important concerns regarding the COVID-19 pandemic."
        },
        {
          "title": "Towards Developing an Automated Attendance Management System using Fingerprint Sensor",
          "link": "https://ieeexplore.ieee.org/document/9350882",
          "authors": "<b>Nafiz Imtiaz Khan</b>, Sumaiya Nuha Mustafina, Farzana Faruk Jhumu, A.H.M Zobyer, Masrur Hasan Mahin, Md. Ariful Islam Tarek, Raiyan Rahman, and Muhammad Nazrul Islam",
          "image": "img/attendance.png",
          "description": "Tracking students' attendance is a regular occurrence in most academic environments. The manual and semiautomated attendance systems are quite time-consuming, inefficient, as well as lacking in security. Thus, the objective of this research is to develop an efficient and secure attendance system that could be beneficial for all educational institutes. As outcomes, an integrated, embedded and fully automated attendance system is developed that makes the use of edge and cloud computing, biometric sensors, and real-time cloud database. The developed system was evaluated with 15 participants in a laboratory environment and found that the proposed system is comparatively more efficient, secure and propitious for educational institutes in tracking attendance."
        },
        {
          "title": "Developing a Machine Learning Based Support System for Mitigating the Suppression Against Women and Children",
          "link": "https://ieeexplore.ieee.org/document/9667924",
          "authors": "Md. Rokonuzzaman Reza, Fabiha Mukarrama Binte Mannan, Dhrubo Barua, Shafayetul Islam, <b>Nafiz Imtiaz Khan</b>, and Sharifa Rania Mahmud",
          "image": "img/reza.png",
          "description": "Violence against women and children has emerged as a significant and growing concern worldwide. To avoid violence, various machine learning (ML) approaches could be used to estimate future violence. The main motive of this study is to provide a central platform for victims, store victim data in a database. In this research, we propose a system that is a web-based tool that stores data on violence against women and children in a database and generates crime forecast results by evaluating the collected data using machine learning techniques. The victim can also get proper information about their rights from this web application. A statistical analysis was carried out on certain datasets and few machine learning model were implemented and the best performed model was decided based on some performance measurement metrics where XG Boost (XB) performed well among others (R-squared test 0.99). Ultimately the XB model has been utilized to generate the forecasting crime report, thereby reducing the level of crime. Government and other law enforcement agencies can predict the future consequences of violence from the system and help victims to get proper justice and settlement. This web application is a support system that may greatly assist women in many parts of their daily lives while also resuming violence against women and children."
        },
        {
          "title": "A Framework to Detect and Prevent Cyberbullying from Social Media by Exploring Machine Learning Algorithms",
          "link": "https://ieeexplore.ieee.org/abstract/document/9768450",
          "authors": "Shutonu Mitra, Tasfia Tasnim, Arr Rafi Islam, <b>Nafiz Imtiaz Khan</b>, and Shajahan Majib",
          "image": "img/sm_analysis.png",
          "description": "Social media is the most popular way to meet new people and interact with friends and associates nowadays. But unfortunately, users get subject to bully or harassment while surfing through social media. Over the last decade, cyberbullying surfaced as one of the most significant issues in the digital world. Although significant research has been carried out to identify cyberbullying through text-mining techniques on many online platforms, still there is a long way to have a concrete solution to remove cyberbullying from social media. This paper introduces a way for the prevention of cyberbullying from social media by identification of cyberbullying texts (Twitter only) through sentiment analysis, and also classification of cyberbullying according to bullying characteristics depending on the proposed taxonomy. In this context, a suitable framework consisting of three modules (e.g., user interaction, analytics, and decision making) is proposed to prevent cyberbullying from social media. The user interaction module contains user profiles from where posts and comments are taken to the analytics module, the analytics module generates results according to the type of bully and the decision-making module takes action finally. Temporary/permanent ban on posting or commenting, bully badge shown at the personal profile are the actions proposed. However, in both bully identification and classification case, the Random Forest algorithm with TFIDF embedding has performed better with an F1 score of 80.8 and 58.4 respectively."
        },
        {
          "title": "An Efficient Transfer Learning Model for Predicting Forged (Handwritten) Signature",
          "link": "https://ieeexplore.ieee.org/abstract/document/9768440",
          "authors": "Muhammad Rafsun Sheikh, Tarek Hasan Masud, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam",
          "image": "img/forged.png",
          "description": "Signature fraud around the world is increasing at an alarming rate. Fraud in the signature may harm a person or an organization by false transactions and false document authorization, which may lead to an irreversible loss. Thus, the purpose of this research is to predict forged signature using machine learning techniques. To attain the objective, different state-of-the-art machine learning models, including Neural Network, K-Nearest Neighbors, Support Vector Machine, Decision Tree, and Random Forest Classifier, were developed to classify between fraud and real signatures. The VGG-16 pre-trained model was used to improve the Neural Network's performance. As outcome, the transfer learning based Neural Network model showed the highest accuracy-96.7%, followed by Support Vector Machine (81.7%), K-Nearest Neighbors (71.7%), Random Forest (70.0%), and Decision Tree (68.3%)."
        },
        {
          "title": "Exploring Design Attributes and Development of an Acoustic VR Game to Improve Ethical Values of Visually Impaired People",
          "link": "https://ieeexplore.ieee.org/abstract/document/9824116",
          "authors": "Faria Habib, Tasfhia Fatema, Munswarim Khan, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam",
          "image": "img/vr.png",
          "description": "Despite having a strong desire to understand and mix up with the normal flow in a society, visually impaired people lack the required knowledge of ethical values due to their visual limitations. The objective of this research is to develop an acoustic virtual reality (VR) game to improve the ethical values of visually impaired people. To achieve this objective, user requirements are collected using a semi-structured interview approach. Then, an android based acoustic and interactive VR game is developed using android studio and cloud database. Finally, an evaluation study is conducted involving visually impaired users to validate the performance of the game by measuring the effectiveness and efficiency of the game along with the satisfaction of the users. Evaluation study reveals a moderate effectiveness and efficiency score of the developed game while 87% of participants like to recommend the game to other users. The developed game is expected to be very useful to improve the ethical values of visually impaired people and provide them with the knowledge for better situational awareness."
        },
        {
          "title": "Neurophysiological Feature Based Stress Classification Using Unsupervised Machine Learning Technique",
          "link": "https://link.springer.com/chapter/10.1007/978-981-19-2445-3_42",
          "authors": "Moumita Bhowmik, Naim Ibna Khadem Al Bhuyain, Md. Rokonuzzaman Reza, <b>Nafiz Imtiaz Khan</b>, and Muhammad Nazrul Islam,",
          "image": "img/stress.png",
          "description": "Mental stress is the primary concern of increasing mental health problems and other medical problems like strokes, heart attacks, and ulcers. Thus, identifying and classifying stress at an early age is the prime requirement to avoid such diseases. Although a number of studies focused to predict and classify stress based on neurophysiological (brain wave and heart rate) data and used the supervised machine learning technique, but a little attention has been paid to explore the performances of unsupervised learning techniques in stress prediction. In this article, an unsupervised machine learning approach is proposed to classify mental stress into three categories: acute (low stress), episodic acute (moderate stress), and severe (high stress). The K-means clustering algorithm was used in the proposed methodology to create three different clusters, which depicts the aforementioned stress levels. The goodness of the clustering technique was evaluated by Silhouette Coefficient, and a standard fitness score of 0.76 was achieved."
        },
        {
          "title": "Monitoring the Health and Movement of Quarantined COVID-19 Patients with Wearable Devices",
          "link": "https://link.springer.com/chapter/10.1007/978-3-031-10031-4_10",
          "authors": "Muhammad Nazrul Islam, <b>Nafiz Imtiaz Khan</b>, Nafiz Islam, Samuli Laato and A. K. M. Nazmul Islam",
          "image": "img/chapter.png",
          "description": "This study explores the requirements and possibilities of wearable devices for ensuring and supporting the home quarantine of suspected COVID-19 patients. We adopted a design science research (DSR) approach and conducted a requirement elicitation study through semi-structured interviews with 36 participants including doctors, home quarantined people and local administrative personnel. Based on the analysis of the interview data, we identified some design considerations for the proposed system. Based on these results we developed a proto- type wearable device and a cloud-server solution which we tested with regards to usability and how well the system meets our design goals. The findings suggest the proposed solution to be able to assist in the remote monitoring of the location and health condition of quarantined people, relieving work load from medical doctors as well as quarantine surveillance officials. The designed wearable device is reusable, meaning that once a patient has recovered from the disease, the same device can be used by other patient."
        },
        // {
        //   "title": "CMH Plasma bank",
        //   "link": "",
        //   "authors": "",
        //   "image": "img/childbicrth.jpg",
        //   "description": "CMH Plasma Bank is a platform for managing plasma donors and accumulated plasma in Combined Military Hospital (CMH), situated in Dhaka, Bangladesh. The app works as a database for storing details about donors and plasma information. This app is developed to help patients in CMH to get the required plasma fast. This app also helps doctors to check the availability of plasma in the plasma bank. Eventually, the endeavor of CMH and MIST for making the Plasma bank app enhanced the capability of CMH to give better treatment to COVID-19 Patients"
        // },
        // {
        //   "title": "MAAS: MIST Automated Attendance System",
        //   "link": "",
        //   "authors": "",
        //   "image": "img/vggs.png",
        //   "description": "MIST Automated Attendance System, is an integrated, embedded, and fully automated attendance system that makes use of edge and cloud computing, biometric sensors, and a real-time cloud database."
        // },
        // {
        //   "title": "UVC-PURGE V2.0",
        //   "link": "https://mist.ac.bd/blog/cse/post/uvc_purge_v20-146",
        //   "authors": "",
        //   "image": "img/sfrc1.jpeg",
        //   "description": "UVC-PURGE\u201d is a semi-autonomous UVC disinfection robot to fight against COVID-19 Pandemic. UVC-PURGE is robust, compact, and user-friendly in nature. This robot has been equipped with six T5 UVC (254 nm) lamps to destroy the SARS-CoV-2 virus (coronavirus) effectively in a standard 12\u2019 x 16\u2019 room with a disinfection time of 2-3 minutes. The Robot provides real-time camera feedback for better navigation. While disinfecting this semi-autonomous robot is capable enough to avoid any obstacles in that room. Being fully wireless and controlled by a mobile app or computer, UVC- PURGE is very user-friendly with 1600 square feet of coverage area and provides a battery backup of 2 hours. It is applicable for any indoor environment such as an Empty COVID patient ward, Empty ICU, Operation Theatre, Office room, Classroom, Corridor, Personal Apartment, etc."
        // },
        // {
        //   "title": "AFMC Admission Test System",
        //   "link": "https://mist.ac.bd/department/cse/announcement/346/department_of_cse_successfully_conducted_the_armed_forces_medical_college_afmc_admission_test_2021",
        //   "authors": "",
        //   "image": "img/uvc1.gif",
        //   "description": "AFMC Admission Test Module is developed for conducting the yearly AFMC Entrance exam. The software\n            module generates randomized MCQ questions for all the students, registered for the admission test. Thus\n            each of the students, participating in the exam, appears on the test with a unique set of questions. Next, the\n            solution evaluates each unique answer script and provides the students\u2019 ranking based on their merit. The\n            software has been used for conducting the AFMC admission Test 2021, where the number of candidates was\n            approximately 30,000."
        // },
        // {
        //   "title": "M-OMR: MIST OMR-Based Exam System",
        //   "link": "",
        //   "authors": "",
        //   "image": "img/bolt1.png",
        //   "description": "M-OMR is a generic system for conducting OMR Based exams. The system generates OMR sheets for each\n            individual candidate participating in the exam. Next, the system evaluates the OMR sheets by enumerating\n            subject-wise marking for each student and provides students\u2019 ranking based on their merit."
        // },
        // {
        //   "title": "C-Archive: MIST CSE Department Data Archive",
        //   "link": "",
        //   "authors": "",
        //   "image": "img/failure1.png",
        //   "description": "The CSE Department Data Archive is a collaborative effort of students and faculty members of the CSE\n            Department, MIST to keep the memories of the CSE Department alive. The archive stores detailed infor-\n            mation regarding Projects, Thesis, Activities, Achievements, Labs, Lab equipment, Publications, Student\n            Profiles, and Faculty Profiles of the CSE Department, MIST."
        // }
      ];

    const researchSection = document.getElementById("research-container");
    articles.forEach((article, index) => {
      const isOdd = index % 2 !== 0; // Alternate layout
      const articleHTML = `
        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5 ${isOdd ? 'flex-md-row-reverse' : ''}">
          <div class="col-lg-4 col-md-4 col-sm-12">
            <img class="img-fluid" src="${article.image}" alt="">
          </div>
          <div class="resume-content">
            <h3 class="mb-0"><a href="${article.link}" target="_blank">${article.title}</a></h3>
            <div class="subheading mb-3">${article.authors}</div>
            <p style="text-align: justify;">${article.description}</p>
          </div>
        </div>
      `;
      researchSection.innerHTML += articleHTML;
    });
  });